<#
.SYNOPSIS
Safely cleans temp files on Windows endpoints.

.DESCRIPTION
Removes files from configured temp paths using an age filter, per-file error handling,
logging, optional dry-run, and optional rollback support.

.NOTES
PowerShell version: 5.1
#>

[CmdletBinding()]
param(
    # One or more folders to scan for temporary files.
    [Parameter(Mandatory = $false)]
    [string[]]$Paths = @(
        $env:TEMP,
        (Join-Path -Path $env:WINDIR -ChildPath 'Temp')
    ),

    # Delete only files with LastWriteTime older than this many days.
    [Parameter(Mandatory = $false)]
    [ValidateRange(0, 36500)]
    [int]$OlderThanDays = 0,

    # Show what would be deleted without making changes.
    [Parameter(Mandatory = $false)]
    [switch]$DryRun,

    # Move files to rollback storage before deletion-equivalent action.
    [Parameter(Mandatory = $false)]
    [switch]$EnableRollback,

    # Root folder used to keep rollback copies and manifests.
    [Parameter(Mandatory = $false)]
    [string]$RollbackRoot = "$env:ProgramData\DwpTempCleanup\Rollback",

    # Root folder used to keep timestamped log files.
    [Parameter(Mandatory = $false)]
    [string]$LogRoot = "$env:ProgramData\DwpTempCleanup\Logs",

    # Manifest file path to restore files from a previous rollback-enabled run.
    [Parameter(Mandatory = $false)]
    [string]$RollbackFromManifest
)

Set-StrictMode -Version 2
$ErrorActionPreference = 'Stop'

# Section: Initialize run metadata, log file location, and common helpers.
$runTimestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$runId = [guid]::NewGuid().ToString()

if (-not (Test-Path -LiteralPath $LogRoot)) {
    New-Item -ItemType Directory -Path $LogRoot -Force | Out-Null
}

$logFile = Join-Path -Path $LogRoot -ChildPath ("temp-cleanup_{0}_{1}.log" -f $runTimestamp, $runId)

function Write-Log {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Message,

        [Parameter(Mandatory = $false)]
        [ValidateSet('INFO', 'WARN', 'ERROR')]
        [string]$Level = 'INFO'
    )

    $line = "[{0}] [{1}] {2}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss.fff'), $Level, $Message
    Add-Content -LiteralPath $logFile -Value $line
    Write-Host $line
}

# Section: Builds a rollback-safe path by mirroring source path under rollback storage.
function Get-RollbackPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$SourceFile,

        [Parameter(Mandatory = $true)]
        [string]$SessionRoot
    )

    $fullPath = [System.IO.Path]::GetFullPath($SourceFile)
    $drive = [System.IO.Path]::GetPathRoot($fullPath).TrimEnd('\\').TrimEnd(':')
    $relative = $fullPath.Substring([System.IO.Path]::GetPathRoot($fullPath).Length)
    return Join-Path -Path $SessionRoot -ChildPath (Join-Path -Path $drive -ChildPath $relative)
}

# Section: Verifies if a file appears to be locked by another process.
function Test-IsLocked {
    param(
        [Parameter(Mandatory = $true)]
        [string]$FilePath
    )

    try {
        $stream = [System.IO.File]::Open($FilePath, 'Open', 'Read', 'None')
        $stream.Close()
        return $false
    }
    catch [System.IO.IOException] {
        return $true
    }
    catch {
        return $false
    }
}

# Section: Restores files from a rollback manifest generated by an earlier run.
function Invoke-Rollback {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ManifestPath,

        [Parameter(Mandatory = $true)]
        [switch]$WhatIf
    )

    if (-not (Test-Path -LiteralPath $ManifestPath -PathType Leaf)) {
        throw "Rollback manifest not found: $ManifestPath"
    }

    Write-Log -Message "Starting rollback using manifest: $ManifestPath"

    $rows = Import-Csv -LiteralPath $ManifestPath
    $restored = 0
    $skipped = 0
    $errors = 0

    foreach ($row in $rows) {
        $src = $row.BackupPath
        $dst = $row.OriginalPath

        try {
            if (-not (Test-Path -LiteralPath $src -PathType Leaf)) {
                Write-Log -Level 'WARN' -Message "Rollback skip (backup missing): $src"
                $skipped++
                continue
            }

            if ($WhatIf) {
                Write-Host "[DRY-RUN ROLLBACK] Would restore: $dst"
                Write-Log -Message "Dry-run rollback candidate: $dst"
                $skipped++
                continue
            }

            $dstParent = Split-Path -Path $dst -Parent
            if (-not (Test-Path -LiteralPath $dstParent)) {
                New-Item -ItemType Directory -Path $dstParent -Force | Out-Null
            }

            if (Test-Path -LiteralPath $dst -PathType Leaf) {
                Write-Log -Level 'WARN' -Message "Rollback skip (destination exists): $dst"
                $skipped++
                continue
            }

            Move-Item -LiteralPath $src -Destination $dst -Force
            Write-Log -Message "Rollback restored: $dst"
            $restored++
        }
        catch {
            Write-Log -Level 'ERROR' -Message ("Rollback error for '{0}': {1}" -f $dst, $_.Exception.Message)
            $errors++
        }
    }

    Write-Host ''
    Write-Host 'Rollback Summary'
    Write-Host '---------------'
    Write-Host ("Restored : {0}" -f $restored)
    Write-Host ("Skipped  : {0}" -f $skipped)
    Write-Host ("Errors   : {0}" -f $errors)

    Write-Log -Message ("Rollback summary | Restored={0} Skipped={1} Errors={2}" -f $restored, $skipped, $errors)
}

# Section: Route execution to rollback mode when a manifest is provided.
if ($RollbackFromManifest) {
    Write-Log -Message 'Mode: Rollback'
    Invoke-Rollback -ManifestPath $RollbackFromManifest -WhatIf:$DryRun
    Write-Host ("Log file: {0}" -f $logFile)
    return
}

# Section: Validate and normalize scan paths.
$effectivePaths = @()
foreach ($path in $Paths) {
    if ([string]::IsNullOrWhiteSpace($path)) {
        continue
    }

    try {
        $full = [System.IO.Path]::GetFullPath($path)

        if ($full -match '^[A-Za-z]:\\$') {
            Write-Log -Level 'WARN' -Message "Skipping unsafe root path: $full"
            continue
        }

        if (Test-Path -LiteralPath $full -PathType Container) {
            $effectivePaths += $full
        }
        else {
            Write-Log -Level 'WARN' -Message "Path not found, skipping: $full"
        }
    }
    catch {
        Write-Log -Level 'WARN' -Message ("Invalid path '{0}', skipping. Reason: {1}" -f $path, $_.Exception.Message)
    }
}

if (-not $effectivePaths -or $effectivePaths.Count -eq 0) {
    Write-Log -Level 'WARN' -Message 'No valid paths to scan. Exiting.'
    Write-Host ("Log file: {0}" -f $logFile)
    return
}

# Section: Build cutoff time from age parameter.
$cutoff = (Get-Date).AddDays(-1 * $OlderThanDays)
Write-Log -Message ("Mode: Cleanup | DryRun={0} | EnableRollback={1} | OlderThanDays={2} | Cutoff={3}" -f $DryRun.IsPresent, $EnableRollback.IsPresent, $OlderThanDays, $cutoff)
Write-Log -Message ("Scan paths: {0}" -f ($effectivePaths -join '; '))

# Section: Create rollback session folder and manifest only when enabled and not in dry-run mode.
$rollbackSessionRoot = $null
$manifestFile = $null
$manifestRows = New-Object System.Collections.Generic.List[object]

if ($EnableRollback -and -not $DryRun) {
    $rollbackSessionRoot = Join-Path -Path $RollbackRoot -ChildPath ("session_{0}_{1}" -f $runTimestamp, $runId)
    New-Item -ItemType Directory -Path $rollbackSessionRoot -Force | Out-Null
    $manifestFile = Join-Path -Path $rollbackSessionRoot -ChildPath 'rollback-manifest.csv'
    Write-Log -Message ("Rollback session folder: {0}" -f $rollbackSessionRoot)
}

# Section: Initialize summary counters for final reporting.
$summary = [ordered]@{
    ScannedFiles    = 0
    EligibleFiles   = 0
    DeletedFiles    = 0
    RolledBackFiles = 0
    DryRunFiles     = 0
    LockedSkipped   = 0
    OtherSkipped    = 0
    Errors          = 0
}

# Section: Scan files and process each file with isolated try/catch logic.
foreach ($scanPath in $effectivePaths) {
    Write-Log -Message ("Scanning: {0}" -f $scanPath)

    $files = @()
    try {
        $files = Get-ChildItem -LiteralPath $scanPath -File -Recurse -Force -ErrorAction SilentlyContinue
    }
    catch {
        Write-Log -Level 'ERROR' -Message ("Failed to enumerate '{0}': {1}" -f $scanPath, $_.Exception.Message)
        $summary.Errors++
        continue
    }

    foreach ($file in $files) {
        $summary.ScannedFiles++

        try {
            if ($file.LastWriteTime -gt $cutoff) {
                continue
            }

            $summary.EligibleFiles++

            if ($DryRun) {
                Write-Host ("[DRY-RUN] Would remove: {0}" -f $file.FullName)
                Write-Log -Message ("Dry-run candidate: {0}" -f $file.FullName)
                $summary.DryRunFiles++
                continue
            }

            if (Test-IsLocked -FilePath $file.FullName) {
                Write-Log -Level 'WARN' -Message ("Skipped locked file: {0}" -f $file.FullName)
                $summary.LockedSkipped++
                continue
            }

            if ($EnableRollback) {
                $backupPath = Get-RollbackPath -SourceFile $file.FullName -SessionRoot $rollbackSessionRoot
                $backupDir = Split-Path -Path $backupPath -Parent

                if (-not (Test-Path -LiteralPath $backupDir)) {
                    New-Item -ItemType Directory -Path $backupDir -Force | Out-Null
                }

                Move-Item -LiteralPath $file.FullName -Destination $backupPath -Force

                $manifestRows.Add([pscustomobject]@{
                    OriginalPath = $file.FullName
                    BackupPath   = $backupPath
                    MovedAt      = (Get-Date -Format 'o')
                }) | Out-Null

                Write-Log -Message ("Moved to rollback store: {0}" -f $file.FullName)
                $summary.RolledBackFiles++
            }
            else {
                Remove-Item -LiteralPath $file.FullName -Force
                Write-Log -Message ("Deleted: {0}" -f $file.FullName)
                $summary.DeletedFiles++
            }
        }
        catch [System.IO.IOException] {
            Write-Log -Level 'WARN' -Message ("I/O issue, skipped '{0}': {1}" -f $file.FullName, $_.Exception.Message)
            $summary.LockedSkipped++
        }
        catch {
            Write-Log -Level 'ERROR' -Message ("Error processing '{0}': {1}" -f $file.FullName, $_.Exception.Message)
            $summary.Errors++
        }
    }
}

# Section: Persist rollback manifest at end of a rollback-enabled cleanup run.
if ($EnableRollback -and -not $DryRun -and $manifestFile) {
    try {
        $manifestRows | Export-Csv -LiteralPath $manifestFile -NoTypeInformation -Encoding UTF8
        Write-Log -Message ("Rollback manifest created: {0}" -f $manifestFile)
    }
    catch {
        Write-Log -Level 'ERROR' -Message ("Failed to write rollback manifest: {0}" -f $_.Exception.Message)
        $summary.Errors++
    }
}

# Section: Print end-of-run summary for engineers and for ticket notes.
Write-Host ''
Write-Host 'Cleanup Summary'
Write-Host '---------------'
Write-Host ("Scanned files    : {0}" -f $summary.ScannedFiles)
Write-Host ("Eligible files   : {0}" -f $summary.EligibleFiles)
Write-Host ("Deleted files    : {0}" -f $summary.DeletedFiles)
Write-Host ("Moved for rollback: {0}" -f $summary.RolledBackFiles)
Write-Host ("Dry-run files    : {0}" -f $summary.DryRunFiles)
Write-Host ("Locked skipped   : {0}" -f $summary.LockedSkipped)
Write-Host ("Other skipped    : {0}" -f $summary.OtherSkipped)
Write-Host ("Errors           : {0}" -f $summary.Errors)

if ($EnableRollback -and -not $DryRun -and $manifestFile) {
    Write-Host ("Rollback manifest: {0}" -f $manifestFile)
}

Write-Host ("Log file         : {0}" -f $logFile)
Write-Log -Message ("Cleanup summary | Scanned={0} Eligible={1} Deleted={2} RolledBack={3} DryRun={4} LockedSkipped={5} OtherSkipped={6} Errors={7}" -f $summary.ScannedFiles, $summary.EligibleFiles, $summary.DeletedFiles, $summary.RolledBackFiles, $summary.DryRunFiles, $summary.LockedSkipped, $summary.OtherSkipped, $summary.Errors)
